services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn scripts.app:app
    envVars:
      - key: PORT
        value: 10000
